keys:
  - &users:
    - &stperc age157v5v40eugqt5rudygpcfqty2e7g9h7pxfffc88m9uxeacdmgyts64h2nw
  - &hosts:
    - &titanium age18dqq72u8ddpju0cr7uzke34js2l74qw0gn66fmk5z37acwxsffesz8q08g
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *stperc
      - *titanium
